title: 90-in-90
description: 

url: https://https://weebaruto.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: /weeblog
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
social:
    github: weebaruto
    email: bobby.mawhinney@gmail.com
    
google_analytics: "UA-58263416-1"
